ALTER TABLE users ADD COLUMN profile_completed BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN age_visible BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN gender_visible BOOLEAN NOT NULL DEFAULT FALSE;
